{{- if eq (include "pelican-panel.createSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pelican-panel.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pelican-panel.labels" . | nindent 4 }}
    app.kubernetes.io/component: panel
  {{- with (include "pelican-panel.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- if not .Values.panel.existingSecret }}
  APP_KEY: {{ include "pelican-panel.appKey" . | quote }}
  {{- if .Values.panel.mail.password }}
  MAIL_PASSWORD: {{ .Values.panel.mail.password | quote }}
  {{- end }}
  {{- end }}
  {{- if and (not .Values.mariadb.enabled) (ne .Values.database.connection "sqlite") .Values.database.password (not .Values.database.existingSecret) }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  {{- end }}
  {{- if and .Values.mariadb.enabled (not .Values.mariadb.auth.existingSecret) }}
  MARIADB_PASSWORD: {{ include "pelican-panel.stickySecretValue" (dict "ctx" . "key" "MARIADB_PASSWORD" "value" .Values.mariadb.auth.password) | quote }}
  MARIADB_ROOT_PASSWORD: {{ include "pelican-panel.stickySecretValue" (dict "ctx" . "key" "MARIADB_ROOT_PASSWORD" "value" .Values.mariadb.auth.rootPassword) | quote }}
  {{- end }}
  {{- if and .Values.redis.enabled .Values.redis.password (not .Values.redis.existingSecret) }}
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  {{- end }}
  {{- if and (not .Values.redis.enabled) .Values.externalRedis.password (not .Values.externalRedis.existingSecret) }}
  REDIS_PASSWORD: {{ .Values.externalRedis.password | quote }}
  {{- end }}
{{- end }}
