apiVersion: v1
kind: Service
metadata:
  name: {{ include "pelican-panel.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pelican-panel.labels" . | nindent 4 }}
    app.kubernetes.io/component: panel
  {{- if or .Values.service.annotations .Values.commonAnnotations }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if .Values.panel.skipCaddy }}
      targetPort: fastcgi
      name: fastcgi
      {{- else }}
      targetPort: http
      name: http
      {{- end }}
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "pelican-panel.panelSelectorLabels" . | nindent 4 }}
